---
title: "p8105_hw3_pm3260"
author: "Pradeeti Mainali"
date: "2024-10-08"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Question 1

```{r}
library(p8105.datasets)
data("ny_noaa")
```
### Description of data set


### Data cleaning

```{r}

```


# Question 2

```{r activity}
# Loading, tidying, merging, and organizing the data sets:

accel_df = 
  read.csv("./data/nhanes_accel.csv") |>
  janitor::clean_names() |>
  drop_na()

covar_df = 
  read.csv("./data/nhanes_covar.csv", skip=4) |>
  janitor::clean_names() |>
  filter(age >= 21) |>
  drop_na() |>
  mutate(
    sex = case_match(
      sex, 
      1 ~ "male",
      2 ~ "female"),
    education = case_match(
      education, 
      1 ~ "Less than high school",
      2 ~ "High school equivalent",
      3 ~ "More than high school"
    ))

activity_df = 
  left_join(
    covar_df, accel_df, by = c("seqn"))
```

#### Creating table for sex x education level

```{r}

```


# Question 3

```{r nyc_bikes}
# Importing, cleaning, and organizing the data sets

```